services:
  postgres:
    image: postgres:17
    container_name: postgres-equipment
    restart: unless-stopped
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - equipment-app
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: minio-equipment
    ports:
      - "9000:9000"      # API MinIO
      - "9001:9001"      # Консоль управления
    #    environment:
    env_file:
      - .env
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/local-dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/src/staticfiles:/static:ro

volumes:
  pg_data:
  minio_data:

networks:
  equipment-app:
    driver: bridge